### ISSUE TITLE
Add option to leave the room and go back to the root page

### ISSUE THREAD

**Issue by Keboo** [Keboo/PointerStar#58]
Though the user could just click the back button it would be nice if we provided a UI mechanism for going back to the root page

**Comment by quattro004** [comment]
The Pointer* header title is a link back to the root page. Should we just style that to look like a button?

![image](https://user-images.githubusercontent.com/209233/210117853-75fec411-07d0-41d4-9bf6-8cf9c7f15cc3.png)

**Comment by Keboo** [comment]
See, it wasn't styled so I had forgotten it did that. Yes, I think simply making it look clickable (either as a link or button would be better)

**Comment by quattro004** [comment]
Styled the home link to look like an image button with the Pointer* logo.
