### ISSUE TITLE
Clear Voter Selection/Focus when votes are cleared

### ISSUE THREAD

**Issue by brucegomes** [Keboo/PointerStar#79]
![Screenshot 2023-01-03 at 10 46 22 AM](https://user-images.githubusercontent.com/16536254/210422650-6f89e18d-97fc-434c-aefd-4829672c07a3.png)

As a voter you can always see what you voted last because the selection/focus never clears. We should clear selection for all voters anytime the facilitator clears the votes

**Comment by Keboo** [comment]
No longer an issue on the latest version
