### ISSUE TITLE
Add time to voting page

### ISSUE THREAD

**Issue by Keboo** [Keboo/PointerStar#8]
There should be a timer on the voting page showing how long it has been since voting has started (or since it was last cleared).

**Comment by quattro004** [comment]
I'm thinking only the facilitator should be able to start/clear the voting timer. But everyone will see the time ticking. Is that a good assumption?

**Comment by akm3** [comment]
No one interacts with the timer. Ever new vote it starts counting, every Time votes are cleared it resets. No one starts or stops the timer

**Comment by quattro004** [comment]
Ok

How will people know when to start voting? The timer is for everyone right? And the timer would start when the first person votes?

**Comment by Keboo** [comment]
The idea with the timer is to give the team an idea if they are spending too much time discussing any particular ticket before coming to a consensus on voting. Really it is just a simple counter from the last time a facilitator clicked the Reset Votes button.
