### ISSUE TITLE
Room Connection Dropping

### ISSUE THREAD

**Issue by brucegomes** [Keboo/PointerStar#89]
* Sometimes during vote, usually after 5min in the room, I click on vote but nothing happens, reloading the page or close and reopening seems to fix it.

attached the logs here.

![image](https://user-images.githubusercontent.com/16536254/211889747-960f92e1-eab1-4be7-88a5-0d4433634445.png)

[console-export-2023-1-11_10-28-52.txt](https://github.com/Keboo/PointerStar/files/10395074/console-export-2023-1-11_10-28-52.txt)

[console-export-2023-1-11_10-34-37.txt](https://github.com/Keboo/PointerStar/files/10395081/console-export-2023-1-11_10-34-37.txt)

**Comment by Keboo** [comment]
Closing for now as this doesn't appear to be a Pointer* issue.
